config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"


  resources :users, only: :show

  resources :items do
    resources :orders, only: [:index, :new, :create]
  end

  resources :items do
  resources :comments, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_name.rb
class CategoryName < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '野菜' },
    { id: 2, name: '果物' },
    { id: 3, name: '調理品' },
    { id: 4, name: '調味料' },
    { id: 5, name: 'お米、パン、麺類' },
    { id: 6, name: 'その他' }
  ]

include ActiveHash::Associations
has_many :items

end

app/models/category_status.rb
class CategoryStatus < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '新鮮' },
    { id: 2, name: '入荷から2,3日' },
    { id: 3, name: '入荷から4,5日' },
    { id: 4, name: '賞味期限切れ間近' },
    { id: 5, name: '要本日中の消費' }
  ]

include ActiveHash::Associations
has_many :items

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :item
  belongs_to :user


  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :orders
  belongs_to :user
  has_many :comments
  has_one_attached :image


  with_options presence: true do
    validates :item_name
    validates :description
    validates :category_name_id
    validates :category_status_id
    validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 }
    validates :image
  end

  with_options numericality: { other_than: 0 } do
    validates :category_name_id
    validates :category_status_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category_status
  belongs_to :category_name

end

app/models/item_qty.rb
class ItemQty < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '1' },
    { id: 2, name: '2' },
    { id: 3, name: '3' },
    { id: 4, name: '4' },
    { id: 5, name: '5' },
    { id: 6, name: '6' },
    { id: 7, name: '7' },
    { id: 8, name: '8' },
    { id: 9, name: '9' },
    { id: 10, name: '10'}
  ]

include ActiveHash::Associations
has_many :ordered_items

end

app/models/order.rb
class Order < ApplicationRecord 
  has_one :ordered_item
  belongs_to :user
  belongs_to :item

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :payment_type
  belongs_to :received_type
  belongs_to :item_qty


end

app/models/order_info.rb
class OrderInfo
  include ActiveModel::Model
  attr_accessor :item_qty, :payment_type, :received_type, :phone, :user_id, :item_id


  with_options presence: true do 
    validates :item_qty, numericality: {other_than: 0 }
    validates :payment_type, numericality: {other_than: 0 }
    validates :received_type, numericality: {other_than: 0 }
    validates :phone, format: { with: /\A[0-9]{10,11}\z/}
    validates :user_id
    validates :item_id
  end

  def save 
    order = Order.create(user_id: user_id, item_id: item_id)

    OrderedItem.create(item_qty: item_qty, payment_type: payment_type, received_type: received_type, phone: phone, order_id: order.id)
  end

end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order

end

app/models/payment_type.rb
class PaymentType < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '現金' },
    { id: 2, name: 'クレジットカード' }
  ]

include ActiveHash::Associations
has_many :orders

end

app/models/received_type.rb
class ReceivedType < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '店舗受け取り' },
    { id: 2, name: 'その他（コメント欄から連絡）' }
  ]

include ActiveHash::Associations
has_many :orders

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :items
  has_many :comments

  with_options presence: true do  
    validates :nickname
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :date_of_birth
  end

  with_options format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ } do
    validates :last_name
    validates :first_name
  end

  with_options format: { with: /\A[ァ-ヶー－]+\z/} do
    validates :last_name_kana
    validates :first_name_kana
  end


  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  private 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :date_of_birth ])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.valid? 
      @comment.save
      ActionCable.server.broadcast "comment_channel", content: @comment
    else
      redirect_to item_path(@comment.item)
    end
  end
  

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, item_id: params[:item_id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:edit,:destroy]
  before_action :move_to_index, only: [:edit]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create 
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
  end

  def show 
    @item = Item.find(params[:id])
    @comment = Comment.new
    @comments = @item.comments.order(created_at: :desc)
    @comments = @item.comments.includes(:user).all

  end


  private 
  def item_params
    params.require(:item).permit(:item_name, :description, :category_name_id, :category_status_id, :price, :image).merge(user_id: current_user.id) 
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_item, only: [:index, :create]



  def index 
    @order_info = OrderInfo.new
  end


  def create
    @order_info = OrderInfo.new(order_params)
    if @order_info.valid?
      @order_info.save
      redirect_to root_path
    else
      render :index
    end


    # @order = Order.create(order_params)
    # OrderedItem.create(ordered_item_params)
    # redirect_to root_path
  end

  private

  def order_params
    params.require(:order_info).permit(:item_qty, :payment_type, :received_type, :phone).merge(user_id: current_user.id, item_id: params[:item_id])
    # params.permit(:order).merge(user_id: current_user.id, item_id: params[:item_id])
  end

  # def ordered_item_params 
  #   params.permit(:item_qty, :payment_type, :received_type, :phone).merge(order_id: @order.id)


  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/controllers/users_controler.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item, local: true do |f|%>
  <div class="field">
    <%= f.label :item_name, "商品名" %><br />
    <%= f.text_field :item_name, id:"item_name" %>
  </div>

  <div class="field">
    <%= f.label :descripton, "商品説明" %><br />
    <%= f.text_area :description, class: :form__text, id:"item_description" %>
  </div>

  <div class="field">
    <%= f.label :category_name_id, "カテゴリー" %><br />
    <%= f.collection_select(:category_name_id, CategoryName.all, :id, :name, {}, {class:"input-default", id:"category_name_id"}) %>

  </div>

  <div class="field">
    <%= f.label :category_status_id, "商品の状態" %><br />
    <%= f.collection_select(:category_status_id, CategoryStatus.all, :id, :name, {}, {class:"input-default", id:"category_status_id"}) %>
  </div>

  <div class="field">
    <%= f.label :price, "値段" %><br />
    <%= f.text_field :price, class: :form__text, id:"item_price" %>
  </div>

  <div class="field">
    <%= f.label :image, "商品の画像" %><br />
    <%= f.file_field :image, id:"item_image" %>
  </div>

  <div class="actions">
    <%= f.submit "出品する", class: :form__btn  %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="card">
  <%= link_to image_tag(item.image, class: :card__img), item_path(item.id) %>
  <div class="card__body">
    <%= link_to item.item_name, item_path(item.id), class: :card__title %>
    <p class="card__summary">
      <%= item.price %>円 <br>
      <%= item.description %>
    </p>
    <%= link_to item.user.nickname, user_path(item.user), class: :card__user %>
  </div>
</div>

app/views/items/_prototype.html.erb
<div class="card">
  <%= link_to image_tag("プロトタイプの画像", class: :card__img ), root_path%>
  <div class="card__body">
    <%= link_to "プロトタイプのタイトル", root_path, class: :card__title%>
    <p class="card__summary">
      <%= "プロトタイプのキャッチコピー" %>
    </p>
    <%= link_to "by プロトタイプの投稿者名", root_path, class: :card__user %>
  </div>
</div>

app/views/items/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/items/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">商品編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "items/form", locals: {items: @item} %>
    </div>
    
  </div>
</div>

app/views/items/index.html.erb
<main class="main">
      <div class="side_bar_content">
       <aside>
        <h2 class="side_title">初めての方</h2>
          <div class="side_bar_section">
            <ul class= "sub_menu">
             <li><a href="public/smartglutton.html.erb">SmartGluttonとは</a></li>
             <li><a href="">フードロスについて</a></li>
             <li><a href="">商品検索</a></li>
             <li><a href="">リスト</a></li>
            </ul>
          </div>
          <h2 class="side_title">商品を買う</h2>
          <div class="side_bar_section">
            <ul class="sub_menu">
             <li><a href="">商品検索</a></li>
             <li><a href="">商品一覧</a></li>
             <li><a href="">買い物かご</a></li>
            </ul>
          </div>
          <h2 class="side_title">商品を売る</h2>
          <div class="side_bar_section">
            <ul class= "sub_menu">
             <li><a href="">売りたい方</a></li>
             <li><a href="">商品出品</a></li>
            </ul>
          </div>
        </aside>
      </div>
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
       <div class="greeting"> 
          こんにちは、
         <%= link_to "#{current_user.nickname}さん", "/users/#{current_user.id}", class: :greeting__link%>
       </div> 
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%= render partial: "item", collection: @items %>
    </div>
  </div>

</main>

app/views/items/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">商品出品</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { item: @item } %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<main class="main">
  <div class="inner">
    <div class="smaglu__wrapper">
      <p class="smaglu__hedding">
        <%= @item.item_name%>
      </p>
      <%= link_to "by #{@item.user.nickname}さん", user_path(@item.user), class: :smaglu__user %>
      <%# 投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <% if user_signed_in? && current_user.id == @item.user_id %>
        <div class="smaglu__manage">
          <%= link_to "編集する", edit_item_path(@item.id), class: :smaglu__btn %>
          <%= link_to "削除する", item_path(@item.id), method: :delete, class: :smaglu__btn %>
        </div>
        <% end %>
      <%# // 投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="smaglu__image">
        <%= image_tag @item.image %>
      </div>
      <div class="item-price-box">
      <span class="item-price"> ¥
        <%= @item.price %>
      </span>
      <%= link_to "カートに進む", item_orders_path(@item.id) ,class: :item_red_btn %>
    </div>
      </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category_name.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.category_status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の説明</th>
          <td class="detail-value"><%= @item.description %></td>
        </tr>
      </tbody>
    </table>
      <div class="smaglu__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <%= form_with model: [@item, @comment], local: true do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
            <div id= 'comments'>
             <% @comments.reverse_each do |comment| %>
              <div class="comment">
                <p><%= comment.text %></p> 
                    <a href="/users/#{comment.user_id}"><%= "・""#{comment.user.nickname}" %></a>
              </div>
              <% end %> 
            </div>
          <% end %> 
      </div>
    </div>
  </div>
</main>

app/views/items/update.html.erb
<main class="main">
  <div class="inner">
    <div class="contents row">
      <div class="success">
        <h3>更新が完了しました。</h3>
        <a class="btn" href="/">投稿一覧へ戻る</a>
      </div>
    </div>
  </div>
</main>

app/views/orders/create.html.erb
<div class="contents row">
  <div class="success">
  <h3>購入が完了しました。</h3>
  <a class="btn" href="/">商品一覧へ戻る</a>
  </div>
</div>

app/views/orders/index.html.erb
<%# <div class='transaction-contents'> %>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
     <div class='buy-item-img'>
      <%= image_tag @item.image %>
      </div>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @item.item_name %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= @item.price %></p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>



    <%= form_with model: @order_info, url: item_orders_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
   
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        購入商品
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">個数</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:item_qty, ItemQty.all, :id, :name, {}, {class:"input-default", id:"item-item_qty"}) %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">支払い方法</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:payment_type, PaymentType.all, :id, :name, {}, {class:"input-default", id:"item-payment_type"}) %>
      </div>

    

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">受け取り方法</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:received_type, ReceivedType.all, :id, :name, {}, {class:"input-default", id:"item-received_type"}) %>
      </div>

      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= @item.price %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  <%# </div> %>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{current_user.nickname}さん" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <%# <td class="table__col2"><%= @user.name %></td> %>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <%# <td class="table__col2"><%= @user.profile %></td> %>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <%# <td class="table__col2"><%= @user.occupation %></td> %>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <%# <td class="table__col2"><%= @user.position %></td> %>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%# <%= item.user.nickname + "さんのプロトタイプ"%> %>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%# <%= render partial: "prototypes/prototype", collection: @prototypes %> %>
      </div>
    </div>
  </div>
</div>