config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"


  resources :users, only: :show

  resources :items do
    resources :orders, only: [:index, :new, :create]
  end

  resources :items do
  resources :comments, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_name.rb
class CategoryName < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '野菜' },
    { id: 2, name: '果物' },
    { id: 3, name: '調理品' },
    { id: 4, name: '調味料' },
    { id: 5, name: 'お米、パン、麺類' },
    { id: 6, name: 'その他' }
  ]

include ActiveHash::Associations
has_many :items

end

app/models/category_status.rb
class CategoryStatus < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '新鮮' },
    { id: 2, name: '入荷から2,3日' },
    { id: 3, name: '入荷から4,5日' },
    { id: 4, name: '賞味期限切れ間近' },
    { id: 5, name: '要本日中の消費' }
  ]

include ActiveHash::Associations
has_many :items

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :item
  belongs_to :user


  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :orders
  belongs_to :user
  has_many :comments
  has_one_attached :image


  with_options presence: true do
    validates :item_name
    validates :description
    validates :category_name_id
    validates :category_status_id
    validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9_999_999 }
    validates :image
  end

  with_options numericality: { other_than: 0 } do
    validates :category_name_id
    validates :category_status_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category_status
  belongs_to :category_name

end

app/models/item_qty.rb
class ItemQty < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '1' },
    { id: 2, name: '2' },
    { id: 3, name: '3' },
    { id: 4, name: '4' },
    { id: 5, name: '5' },
    { id: 6, name: '6' },
    { id: 7, name: '7' },
    { id: 8, name: '8' },
    { id: 9, name: '9' },
    { id: 10, name: '10'}
  ]

include ActiveHash::Associations
has_many :ordered_items

end

app/models/order.rb
class Order < ApplicationRecord 
  has_one :ordered_item
  belongs_to :user
  belongs_to :item

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :payment_type
  belongs_to :received_type
  belongs_to :item_qty


end

app/models/order_info.rb
class OrderInfo
  include ActiveModel::Model
  attr_accessor :item_qty, :payment_type, :received_type, :phone, :user_id, :item_id


  with_options presence: true do 
    validates :item_qty, numericality: {other_than: 0 }
    validates :payment_type, numericality: {other_than: 0 }
    validates :received_type, numericality: {other_than: 0 }
    validates :phone, format: { with: /\A[0-9]{10,11}\z/}
    validates :user_id
    validates :item_id
  end

  def save 
    order = Order.create(user_id: user_id, item_id: item_id)

    OrderedItem.create(item_qty: item_qty, payment_type: payment_type, received_type: received_type, phone: phone, order_id: order.id)
  end

end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order

end

app/models/payment_type.rb
class PaymentType < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '現金' },
    { id: 2, name: 'クレジットカード' }
  ]

include ActiveHash::Associations
has_many :orders

end

app/models/received_type.rb
class ReceivedType < ActiveHash::Base

  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '店舗受け取り' },
    { id: 2, name: 'その他（コメント欄から連絡）' }
  ]

include ActiveHash::Associations
has_many :orders

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :items
  has_many :comments

  with_options presence: true do  
    validates :nickname
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :date_of_birth
  end

  with_options format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ } do
    validates :last_name
    validates :first_name
  end

  with_options format: { with: /\A[ァ-ヶー－]+\z/} do
    validates :last_name_kana
    validates :first_name_kana
  end


  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:edit,:destroy]
  before_action :move_to_index, only: [:edit]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create 
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
  end

  def show 
    @item = Item.find(params[:id])
    @comment = Comment.new
    @comments = @item.comments.order(created_at: :desc)
    @comments = @item.comments.includes(:user).all

  end


  private 
  def item_params
    params.require(:item).permit(:item_name, :description, :category_name_id, :category_status_id, :price, :image).merge(user_id: current_user.id) 
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_item, only: [:index, :create]



  def index 
    @order_info = OrderInfo.new
  end


  def create
    @order_info = OrderInfo.new(order_params)
    if @order_info.valid?
      @order_info.save
      redirect_to root_path
    else
      render :index
    end


    # @order = Order.create(order_params)
    # OrderedItem.create(ordered_item_params)
    # redirect_to root_path
  end

  private

  def order_params
    params.require(:order_info).permit(:item_qty, :payment_type, :received_type, :phone).merge(user_id: current_user.id, item_id: params[:item_id])
    # params.permit(:order).merge(user_id: current_user.id, item_id: params[:item_id])
  end

  # def ordered_item_params 
  #   params.permit(:item_qty, :payment_type, :received_type, :phone).merge(order_id: @order.id)


  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/controllers/users_controler.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/html_contents/smartglutton.html.erb
<!DOCTYPE html>


<h1>SmartGlutton </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SmartGlutton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
        <title>SmartGlutton</title>
          <div class="nav__left">
            <%= link_to root_path, class: :logo do %>
              <%= image_tag "SmartGlutton-logo.png", class: :logo %> <br>
                <a> SmartGluttonはフードロスを削減するための、フードシェアアプリです</a>
            <% end %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
           <% if user_signed_in? %>
             <div class="nav__right">
               <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %></li>
               <li><%= link_to "商品出品", new_item_path, class: :nav__btn %></li>
                <%= link_to root_path, target: "_blank" do  %>
                 <li><%= image_tag "カートのアイコン素材 (1).png", class: :cart__logo %></li> 
                <% end %> 
             </div>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>

    <footer class="footer">
      <p class="copyright">Copyright © SmartGlutton All rights reserved.</p>
        <div class="footer__right">
          <%= link_to image_tag("E_SDG_logo_without_UN_emblem_horizontal_Transparent_WEB.png", class: :logo), root_path %>
        </div>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li> 
    <% end %>
  </ul>
</div>
<% end %>